
name: CI/CD Pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install fastapi uvicorn pyngrok python-multipart
        pip install joblib pandas numpy jinja2 scikit-learn==1.6.0
        pip install pytest httpx pytest-asyncio

    - name: Run Tests
      run: |
        pytest

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
